gemini_project/gemini_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'gemini_app'

urlpatterns = [
   path('chat-Gemini/',views.gemini_view, name='chat-Gemini'),
   path('',views.home_view, name='home'),
   path('register/',views.register_view, name='register'),
   path('login/',views.login_view, name='login'),
   path('logout/',views.logout_view, name='logout'),

]

gemini_project/gemini_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
   path('', include('gemini_app.urls')),
]

gemini_project/gemini_app/models.py
# # models.py

# from django.contrib.auth.models import AbstractUser
# from django.db import models
# class CustomUser(AbstractUser):
#     first_name = models.CharField(max_length=30)
#     last_name = models.CharField(max_length=30)

gemini_project/gemini_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import  User
from django.forms import ModelForm

# from .models import CustomUser
 
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

gemini_project/gemini_app/views.py
from audioop import reverse
from base64 import b64encode
from django.shortcuts import redirect, render
from django.urls import reverse
from .utils import configure_api
import google.generativeai as genai
from PIL import Image
import io

from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserChangeForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render
from django.contrib.auth.models import User
from .forms import CustomUserCreationForm

from django.contrib.auth.decorators import login_required
# from .models import CustomUser


@login_required(login_url='gemini_app:login')
def gemini_view(request):
    configure_api()
    if request.method == 'POST':
        prompt = request.POST.get('prompt', '')
        image_file = request.FILES.get('image')
        print(image_file)

        if image_file:
            image = Image.open(image_file)
            model = genai.GenerativeModel('gemini-pro-vision')
            response = model.generate_content([prompt, image], stream=True)
            response.resolve()
            generated_text = response.text
        else:
            model = genai.GenerativeModel('gemini-pro')
            response = model.generate_content(prompt)
            generated_text = response.text
    else:
        generated_text = None

    context = {'generated_text': generated_text}
    return render(request, 'gemini_app/chat-Gemini.html', context)

def home_view(request):
    return render(request,'gemini_app/home.html')

from django.contrib import messages

def register_view(request):
    if request.user.is_authenticated:
        return redirect(reverse('gemini_app:chat-Gemini'))

    form = CustomUserCreationForm()
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        
        if password1 != password2:
            messages.error(request, "Passwords do not match")
            return render(request, 'gemini_app/register.html', {'form': form})
        
        if len(password1) < 8 or len(password2) < 8:
            messages.error(request, "Password is too short")
            return render(request, 'gemini_app/register.html', {'form': form})
        
        if form.is_valid():

            form.save()
            messages.success(request, 'Account has been successfully created')
            return redirect('gemini_app:login')
    context = {'form': form,}
    # 'first_name':first_name, 'last_name':last_name
    return render(request, 'gemini_app/register.html',context)


def login_view(request):
    if request.user.is_authenticated:
        return redirect(reverse('gemini_app:chat-Gemini'))

    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user = authenticate(request, username= username, password = password)
        if user is not None:
            login(request, user)
            first_name = user.first_name
            last_name = user.last_name
            return redirect(reverse('gemini_app:chat-Gemini'))
        else:
            messages.info(request, 'username or password is invalid')
    return render(request, 'gemini_app/login.html')


def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect(reverse('gemini_app:home'))
        
    return redirect(reverse('gemini_app:login'))
          

gemini_project/gemini_app/templates/gemini_app/chat-Gemini.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/home.css' %}">
  <title>Sidebar on Hover</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap');

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      font-family: 'Poppins', sans-serif;

    }

    .container {
      margin-left: 200px;
      margin-right: 200px;
      white-space: pre;
      white-space: pre-line;

    }


    .submit-btn:hover {
      background-color: #45a049;
    }

    .input-text {
      width: 750px;
      height: 56px;
      margin: 0 auto;
      /* Center horizontally */
      bottom: 0;
      padding: 10px;
      font-size: 16px;
      border: 2px solid #ccc;
      border-radius: 20px;
      resize: none;
      overflow-y: hidden;
      transition: border-color 0.3s ease;
      box-sizing: border-box;
      position: fixed;
      left: 50%;
      transform: translateX(-50%);
      /* Center horizontally with respect to the viewport */


      padding-right: 85px; /* Provide space for the buttons on the right */
      
    }



    .submit-btn {
      display: inline-block;
      bottom: 9px;
      margin-left: 770px;
      width: 31px;
      height: 33px;
      background-color: #000000;
      border: none;
      border-radius: 5px;
      cursor: pointer;
      position: fixed;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.25);

    }
    
    .submit-btn::before {
      content: "";
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%) rotate(-90deg);
      width: 14px;
      height: 3px;
      background-color: #ffffff;
    }
    
    .submit-btn::after {
      content: "";
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%) rotate(-45deg);
      width: 10px;
      height: 10px;
      border-top: 3px solid #ffffff;
      border-right: 3px solid #ffffff;
    }
    

    .input-text:focus {
      outline: none;
      border-color: #4CAF50;
    }

    .input-text::placeholder {
      color: #999;
    }

    p {
      display: block;
      width: 80%;
      margin: 0 auto;
      /* Center align the paragraphs */
      font-size: 16px;
      line-height: 1.5;
    }


    .file-input-container {
      display: inline-block;
      position: fixed;
      cursor: pointer;
      bottom: -15px;
      margin-left: 730px;


      gap: 4px; /* Adjust the gap between the file input and icon */
      position: fixed; /* Position the file input container absolutely */

    }
    
    .file-input {
      position: absolute;
      width: 100%;
      height: 100%;
      top: 0;
      left: 0;
      opacity: 0;
      cursor: pointer;
    }
    
    .icon-container {
      width: 34px;
      height: 34px;
      background-color: #f0f0f0;
      border-radius: 8px;
      display: flex;
      justify-content: center;
      align-items: center;
    }
    
    .icon {
      width: 18px;
      height: 18px;
      background-color: #333;
      -webkit-mask-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M16.5 6v11.5c0 2.21-1.79 4-4 4s-4-1.79-4-4V5c0-1.38 1.12-2.5 2.5-2.5s2.5 1.12 2.5 2.5v10.5c0 .55-.45 1-1 1s-1-.45-1-1V6H10v9.5c0 1.38 1.12 2.5 2.5 2.5s2.5-1.12 2.5-2.5V5c0-2.21-1.79-4-4-4S7 2.79 7 5v12.5c0 3.04 2.46 5.5 5.5 5.5s5.5-2.46 5.5-5.5V6h-1.5z'/%3E%3C/svg%3E");
      mask-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M16.5 6v11.5c0 2.21-1.79 4-4 4s-4-1.79-4-4V5c0-1.38 1.12-2.5 2.5-2.5s2.5 1.12 2.5 2.5v10.5c0 .55-.45 1-1 1s-1-.45-1-1V6H10v9.5c0 1.38 1.12 2.5 2.5 2.5s2.5-1.12 2.5-2.5V5c0-2.21-1.79-4-4-4S7 2.79 7 5v12.5c0 3.04 2.46 5.5 5.5 5.5s5.5-2.46 5.5-5.5V6h-1.5z'/%3E%3C/svg%3E");
      -webkit-mask-size: contain;
      mask-size: contain;
      -webkit-mask-repeat: no-repeat;
      mask-repeat: no-repeat;
      -webkit-mask-position: center;
      mask-position: center;
    }


    .icon-container:hover {
      background-color: #45a049;
    }

    .typing-animation {
      font-size: 48px;
      font-weight: bold;
      color: transparent;
      -webkit-text-stroke: 1px #00bfff;
      overflow: hidden;
      white-space: nowrap;
      animation: typing 4s steps(30, end) forwards, color-change 4s infinite alternate;
    }
    
    @keyframes typing {
      from { width: 0; }
      to { width: 100%; }
    }
    
    @keyframes color-change {
      0% { color: transparent; -webkit-text-stroke: 1px #00bfff; }
      50% { color: #00bfff; -webkit-text-stroke: 1px transparent; }
      100% { color: transparent; -webkit-text-stroke: 1px #00bfff; }
    }


    .typing-animation-1 {
      font-size: 48px;
      font-weight: bold;
      color: transparent;
      background: linear-gradient(90deg, transparent, #00bfff, transparent); /* Add shimmer effect */
      background-size: 400% 100%;
      overflow: hidden;
      white-space: nowrap;
      animation: typing 4s steps(30, end) forwards, shimmer 4s infinite linear;
    }
    
    @keyframes typing {
      from {
        width: 0;
      }
      to {
        width: 100%;
      }
    }
    
    @keyframes shimmer {
      0% {
        background-position: 0% 0;
      }
      100% {
        background-position: 100% 0;
      }
    }
    
    .log-out{
      
    text-decoration: none

    }



  </style>
</head>

<body>
 
  
  <div class="container" id="container">
    <div class="text-content" id="content">
      {% if generated_text %}
      <h2>Generated Text:</h2>
      <p>{{ generated_text }}</p>
      {% endif %}
    </div>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="container-1">
        
        
        <span>Hello, {{ user.first_name }} {{ user.last_name }}</span>
        <span ><a class="log-out"  href="{% url 'gemini_app:logout' %}"> logout</a></span>
        <h1 class="typing-animation">How can I help you today?</h1>
        <textarea type="text" id="input-text" class="input-text" name="prompt" required placeholder="Replay to Gemini"></textarea> 
        <!-- <input type="text" id="prompt" name="prompt" required> -->
        <!-- <input type="file" id="image" name="image" accept="image/*"> -->
        <label class="file-input-container">
          <input type="file" id="image" class="file-input" name="image" accept="image/*"/>
          <div class="icon-container">
            <div class="icon"></div>
          </div>
        </label>
        <button type="submit" id='submit-btn' class="submit-btn"></button>
      </div>
    </form> 
  </div> 




  <script>
    window.onload = function() {
      var content = document.getElementById("content").innerHTML;
      content = content.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>");
      content = content.replace(/^\*+/gm, '');
  
      // Remove leading asterisk from each line within the content
      content = content.replace(/^\s*\*+/gm, '');
      content = content.replace(/\*\*\*(.*?)\*\*/g, "<strong style='font-size: 0.8em;'>$1</strong><br><br>");
      document.getElementById("content").innerHTML = content;
  };
  const textarea = document.getElementById('input-text');
    const maxHeight = 200; // Set the maximum height limit (in pixels)

    textarea.addEventListener('input', adjustHeight);

    function adjustHeight() {
      textarea.style.height = 'auto'; // Reset the height to allow for shrinking
      let newHeight = `${textarea.scrollHeight}px`; // Get the desired height based on content

      // Check if the desired height exceeds the maximum height limit
      if (textarea.scrollHeight > maxHeight) {
        newHeight = `${maxHeight}px`; // Set the height to the maximum limit
      }

      textarea.style.height = newHeight; // Set the new height
    }
  </script>
  {% block start %}
  {% endblock %}
</body>
</html>

gemini_project/gemini_app/templates/gemini_app/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>login</title>
  <link rel="stylesheet" href="{% static 'css/login.css' %}">

</head>
<body>
  <div class="container">
    <div class="register-card">
      <h2 class="register-title">Login</h2>
      {% for message in messages %}
        {{ message }}
      {% endfor %}

      <form method="POST" action="{% url 'gemini_app:login' %}" enctype="multipart/form-data" class="register-form">
        {% csrf_token %}
        <div class="form-group">
          <label class="form-label" for="username">Username</label>
          <div class="form-input-wrapper">
            <input type="text" name="username" class="form-input">
          </div>
        </div>

        <div class="form-group">
          <label class="form-label" for="password">Password</label>
          <div class="form-input-wrapper">
            <input type="password" name="password" class="form-input">
          </div>
        </div>

        <button type="submit" class="register-btn">Login</button>
        <span>Don't have an Account? <a href="{% url 'gemini_app:register' %}">Sign Up</a></span>
      </form>
    </div>
</div>
      
</body>
</html>

gemini_project/gemini_app/templates/gemini_app/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>User Registration Form</title>
  <link rel="stylesheet" href="{% static 'css/login.css' %}">

</head>
<body>
  <div class="container">
    <div class="register-card">
      <h2 class="register-title">Register</h2>
      {% for message in messages %}
        {{ message }}
      {% endfor %}

      <form method="POST" action="{% url 'gemini_app:register' %}" enctype="multipart/form-data" class="register-form">
        {% csrf_token %}
        
        <div class="form-group">
          <label class="form-label" for="username">Username</label>
          <div class="form-input-wrapper">
            {{ form.username }}
          </div>
        </div>

        <div class="form-group">
          <label class="form-label" for="first_name">First Name</label>
          <div class="form-input-wrapper">
            {{ form.first_name }}
          </div>
        </div>

        <div class="form-group">
          <label class="form-label" for="last_name">Last Name</label>
          <div class="form-input-wrapper">
            {{ form.last_name }}
          </div>
        </div>

        <div class="form-group">
          <label class="form-label" for="email">Email</label>
          <div class="form-input-wrapper">
            {{ form.email }}
          </div>
        </div>

        <div class="form-group">
          <label class="form-label" for="password1">Password</label>
          <div class="form-input-wrapper">
            {{ form.password1 }}
          </div>
        </div>

        <div class="form-group">
          <label class="form-label" for="password2">Confirm Password</label>
          <div class="form-input-wrapper">
            {{ form.password2 }}
          </div>
        </div>

        <button type="submit" class="register-btn">Register</button>
        <span>Already have an Account? <a href="{% url 'gemini_app:login' %}">Sign In</a></span>
      </form>
    </div>
</div>

      
</body>
</html>